export const loc = [
  { id: 1, city: "Kiev", country: "United kingdom" },
  { id: 2, city: "Kiev", country: "Ukraine" },
  { id: 3, city: "", country: "India" },
  { id: 4, city: "", country: "China" },
  { id: 5, city: "", country: "Poland" },
  { id: 6, city: "", country: "Russia" },
  { id: 7, city: "", country: "Canada" },
  { id: 8, city: "Krakow", country: "" },
  { id: 9, city: "Bangalore", country: "" },
];
export const alphabets = [
  "A",
  "B",
  "C",
  "D",
  "E",
  "F",
  "G",
  "H",
  "I",
  "J",
  "K",
  "L",
  "M",
  "N",
  "O",
  "P",
  "Q",
  "R",
  "S",
  "T",
  "U",
  "V",
  "W",
  "X",
  "Y",
  "Z",
];
